import { Home } from "@/modules/home/pages/Home";

export const metadata = {
  title: "Sathira's Grotto",
  description: "Generated by create next app",
};

export default function Page() {
  return <Home />;
}
