import { Devlog } from "@/modules/devlog/pages/Devlog"

export const dynamicParams = false

export const metadata = {
    title: "Sathira's Grotto",
    description: "Generated by create next app",
};

interface Props {
    params: Promise<{ slug: string }>
}

export default async function Page(props: Props) {
    const slug = (await props.params).slug
    
    const { default: DevlogContent, ...metadata } = await import(`@/content/${slug}/main.mdx`)

    return (
        <Devlog>
            <DevlogContent />
        </Devlog>
    )
}